#!/usr/bin/env bash

DIR=$1

for file in "$DIR"/*.py; do
  filename=$(basename "$file")

  adb push "$file" /sdcard/Download/"$filename"

  adb shell "su -c 'cp /sdcard/Download/$filename /data/data/com.exteragram.messenger/files/plugins/'"
  adb shell "su -c 'chmod 666 /data/data/com.exteragram.messenger/files/plugins/$filename'"
done

adb shell "su -c 'rm -rf /data/data/com.exteragram.messenger/files/plugins/__pycache__/'"

adb logcat -c
adb logcat *:D | grep "PyObject"
